import { useCallback } from 'react'

// License data is automatically generated from dependencies
// To update: run `pnpm license:update` or `node scripts/update-licenses.js`
import rendererLicenseData from '../../../../../../../docs/licenses/app-licenses.json'
// Electron(main) license data exists only for Electron builds; AboutTab will conditionally show it
// The file is generated by scripts/update-licenses.js as app-licenses-electron.json
import electronLicenseData from '../../../../../../../docs/licenses/app-licenses-electron.json'
import pkg from '../../../../../../../package.json'
import { AppInfoSection } from './about/AppInfoSection'
import { DependenciesSection } from './about/DependenciesSection'
import { LicenseStatsSection } from './about/LicenseStatsSection'
import type { AppInfo, AppLicenseData, LicenseStats } from './about/types'
import { UpdateSection } from './about/UpdateSection'
import { VersionsSection } from './about/VersionsSection'

export const AboutTab = () => {
  const getAppInfo = (): AppInfo => {
    return {
      name: 'Torrent Vibe',
      version: pkg.version,
      description: 'Modern BitTorrent Client',
      author: 'Innei',
      platform: ELECTRON ? 'Application' : 'Web UI',
    }
  }

  const appInfo = getAppInfo()

  const calculateLicenseStats = useCallback(
    (data: AppLicenseData): LicenseStats[] => {
      return data.licenseGroups.map(group => ({
        license: group.license,
        count: group.count,
        percentage: Math.round((group.count / data.totalLibraries) * 100),
      }))
    },
    [],
  )

  return (
    <div className="space-y-4">
      {/* Terminal Header */}
      <div className="font-mono text-sm">
        <div className="flex items-center space-x-2 mb-4">
          <span className="text-accent">$</span>
          <span className="text-accent font-medium">torrent-vibe --about</span>
        </div>
        <div className="border-t border-border mb-4" />
      </div>

      {/* Application Information */}
      <AppInfoSection appInfo={appInfo} />
      {ELECTRON && <VersionsSection />}

      {/* Update Section */}
      {ELECTRON && <UpdateSection />}

      {/* Renderer Dependencies */}
      {rendererLicenseData && rendererLicenseData.licenses.length > 0 && (
        <DependenciesSection
          commandLabel="torrent-vibe --dependencies renderer"
          dependencies={rendererLicenseData.licenses}
        />
      )}

      {/* Electron (Main) Dependencies - only in Electron env */}
      {ELECTRON
        && electronLicenseData
        && electronLicenseData.licenses.length > 0 && (
        <DependenciesSection
          commandLabel="torrent-vibe --dependencies electron"
          dependencies={electronLicenseData.licenses}
        />
      )}

      {/* License Statistics for Renderer */}
      {rendererLicenseData && (
        <LicenseStatsSection
          commandLabel="torrent-vibe --licenses"
          totalDependencies={
            (rendererLicenseData as AppLicenseData).totalLibraries
          }
          licenseStats={calculateLicenseStats(
            rendererLicenseData as AppLicenseData,
          )}
        />
      )}

      {/* License Statistics for Electron (Main) - only in Electron env */}
      {ELECTRON && electronLicenseData && (
        <LicenseStatsSection
          commandLabel="torrent-vibe --licenses electron"
          totalDependencies={
            (electronLicenseData as AppLicenseData).totalLibraries
          }
          licenseStats={calculateLicenseStats(
            electronLicenseData as AppLicenseData,
          )}
        />
      )}
    </div>
  )
}
