import {
  AddedOnCellRenderer,
  AutoTmmCellRenderer,
  AvailabilityCellRenderer,
  CategoryCellRenderer,
  CommentCellRenderer,
  CompletionCellRenderer,
  ContentPathCellRenderer,
  DlLimitCellRenderer,
  DlspeedCellRenderer,
  DownloadedCellRenderer,
  DownloadedSessionCellRenderer,
  DownloadPathCellRenderer,
  EtaCellRenderer,
  FirstLastPiecePrioCellRenderer,
  ForceStartCellRenderer,
  HasMetadataCellRenderer,
  InactiveSeedingTimeLimitCellRenderer,
  InfohashV1CellRenderer,
  InfohashV2CellRenderer,
  LastActivityCellRenderer,
  MagnetUriCellRenderer,
  NameCellRenderer,
  PeersCellRenderer,
  PopularityCellRenderer,
  PriorityCellRenderer,
  PrivateCellRenderer,
  ProgressCellRenderer,
  RatioCellRenderer,
  RatioLimitCellRenderer,
  ReannounceCellRenderer,
  RemainingCellRenderer,
  RootPathCellRenderer,
  SavePathCellRenderer,
  SeedingTimeCellRenderer,
  SeedingTimeLimitCellRenderer,
  SeedsCellRenderer,
  SeenCompleteCellRenderer,
  SelectCellRenderer,
  SequentialDownloadCellRenderer,
  SizeCellRenderer,
  StateCellRenderer,
  SuperSeedingCellRenderer,
  TagsCellRenderer,
  TimeActiveCellRenderer,
  TotalSizeCellRenderer,
  TrackerCellRenderer,
  TrackersCountCellRenderer,
  UpLimitCellRenderer,
  UploadedCellRenderer,
  UploadedSessionCellRenderer,
  UpspeedCellRenderer,
} from './renderers'

// Static mapping object - also defined at module level
export const CELL_RENDERERS = {
  // Built-in
  select: SelectCellRenderer,
  // Existing columns
  name: NameCellRenderer,
  size: SizeCellRenderer,
  progress: ProgressCellRenderer,
  dlspeed: DlspeedCellRenderer,
  upspeed: UpspeedCellRenderer,
  eta: EtaCellRenderer,
  ratio: RatioCellRenderer,
  state: StateCellRenderer,
  priority: PriorityCellRenderer,
  tracker: TrackerCellRenderer,
  category: CategoryCellRenderer,
  tags: TagsCellRenderer,
  added_on: AddedOnCellRenderer,
  completion_on: CompletionCellRenderer,
  last_activity: LastActivityCellRenderer,
  save_path: SavePathCellRenderer,
  downloaded: DownloadedCellRenderer,
  uploaded: UploadedCellRenderer,
  num_seeds: SeedsCellRenderer,
  num_leechs: PeersCellRenderer,
  amount_left: RemainingCellRenderer,
  time_active: TimeActiveCellRenderer,
  seeding_time: SeedingTimeCellRenderer,
  // qBittorrent standard fields (new)
  auto_tmm: AutoTmmCellRenderer,
  availability: AvailabilityCellRenderer,
  content_path: ContentPathCellRenderer,
  dl_limit: DlLimitCellRenderer,
  up_limit: UpLimitCellRenderer,
  downloaded_session: DownloadedSessionCellRenderer,
  uploaded_session: UploadedSessionCellRenderer,
  magnet_uri: MagnetUriCellRenderer,
  f_l_piece_prio: FirstLastPiecePrioCellRenderer,
  force_start: ForceStartCellRenderer,
  ratio_limit: RatioLimitCellRenderer,
  seeding_time_limit: SeedingTimeLimitCellRenderer,
  seen_complete: SeenCompleteCellRenderer,
  seq_dl: SequentialDownloadCellRenderer,
  super_seeding: SuperSeedingCellRenderer,
  total_size: TotalSizeCellRenderer,
  // qBittorrent 5.0+ fields
  infohash_v1: InfohashV1CellRenderer,
  infohash_v2: InfohashV2CellRenderer,
  popularity: PopularityCellRenderer,
  comment: CommentCellRenderer,
  private: PrivateCellRenderer,
  has_metadata: HasMetadataCellRenderer,
  reannounce: ReannounceCellRenderer,
  root_path: RootPathCellRenderer,
  download_path: DownloadPathCellRenderer,
  trackers_count: TrackersCountCellRenderer,
  inactive_seeding_time_limit: InactiveSeedingTimeLimitCellRenderer,
} as const
